Repository depromeet/Pumping-iOS, pull requests merged in 2023-05, with the labels that each got.

#28 [Bugfix/#27] GPT 코드리뷰 동작 안됨
  .github/workflows/cr.yml
  Pumping/Projects/Domain/Sources/ContentView.swift
Labels: size/s

#30 [Feat/#29] 온보딩 플로우 구성
  Pumping/Projects/Feature/Onboarding/Interface/Sources/OnboardingNicknameScreen.swift
  Pumping/Projects/Feature/Onboarding/Interface/Sources/OnboardingRootScreen.swift
  Pumping/Projects/Feature/Onboarding/Interface/Sources/OnboardingScreen.swift
  Pumping/Projects/Feature/Onboarding/Interface/Sources/OnboardingSignUpScreen.swift
  Pumping/Projects/Feature/Onboarding/Project.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingCore.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingFirstView.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingNicknameView.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingRootView.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingSecondView.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingSignUpView.swift
  Pumping/Projects/Feature/Onboarding/Sources/OnboardingThirdView.swift
  Pumping/Projects/Feature/Sources/CompositionRoot.swift
  Pumping/Projects/Feature/Sources/RootView.swift
Labels: size/m

#32 [Feat/#31] tuist makefile 적용
  Pumping/.tuist-version
  Pumping/Makefile
  Pumping/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Pumping/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Path+Modules.swift
  Pumping/Plugins/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+Modules.swift
  Pumping/Projects/App/Project.swift
  Pumping/Projects/Core/Network/Project.swift
  Pumping/Projects/Core/Project.swift
  Pumping/Projects/Domain/Health/Project.swift
  Pumping/Projects/Domain/Login/Project.swift
  Pumping/Projects/Domain/Project.swift
  Pumping/Projects/Feature/Home/Project.swift
  Pumping/Projects/Feature/MyPage/Project.swift
  Pumping/Projects/Feature/Onboarding/Project.swift
  Pumping/Projects/Feature/Project.swift
  Pumping/Projects/Feature/SampleFeature/Example/Sources/AppView.swift
  Pumping/Projects/Feature/SampleFeature/Interface/Sources/SampleFeatureInterface.swift
  Pumping/Projects/Feature/SampleFeature/Project.swift
  Pumping/Projects/Feature/SampleFeature/Sources/Source.swift
  Pumping/Projects/Feature/SampleFeature/Testing/Sources/SampleFeatureTesting.swift
  Pumping/Projects/Feature/SampleFeature/Tests/Sources/SampleFeatureTest.swift
  Pumping/Projects/Shared/Project.swift
  Pumping/Projects/WatchShared/Project.swift
  Pumping/Scripts/GenerateModule.swift
  Pumping/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Pumping/Tuist/ProjectDescriptionHelpers/SourceFilesList+Template.swift
  Pumping/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  Pumping/Tuist/Signing/Pumping.Debug.mobileprovision
  Pumping/Tuist/Templates/Example/Example.swift
  Pumping/Tuist/Templates/Example/ExampleSources.stencil
  Pumping/Tuist/Templates/Interface/Interface.stencil
  Pumping/Tuist/Templates/Interface/Interface.swift
  Pumping/Tuist/Templates/Module/Module.swift
  Pumping/Tuist/Templates/Module/Project.stencil
  Pumping/Tuist/Templates/Module/Sources.stencil
  Pumping/Tuist/Templates/Sources/Sources.stencil
  Pumping/Tuist/Templates/Sources/Sources.swift
  Pumping/Tuist/Templates/Testing/Testing.stencil
  Pumping/Tuist/Templates/Testing/Testing.swift
  Pumping/Tuist/Templates/Tests/Tests.stencil
  Pumping/Tuist/Templates/Tests/Tests.swift
  Pumping/graph.png
Labels: size/l

#38 [Feat/#36] Root View 구현
  Projects/Domain/Auth/Interface/Sources/Clients/AuthClient.swift
  Projects/Feature/Home/Interface/Sources/HomeRoot.swift
  Projects/Feature/Home/Interface/Sources/HomeScreen.swift
  Projects/Feature/Home/Sources/HomeRootView.swift
  Projects/Feature/Home/Sources/HomeView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRoot.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageScreen.swift
  Projects/Feature/MyPage/Interface/Sources/UserInfo.swift
  Projects/Feature/MyPage/Interface/Sources/VersionInfo.swift
  Projects/Feature/MyPage/Sources/HomeView.swift
  Projects/Feature/MyPage/Sources/MyPageRootView.swift
  Projects/Feature/MyPage/Sources/UserInfoView.swift
  Projects/Feature/MyPage/Sources/VersionInfoView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingNickname.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingRoot.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingSignUp.swift
  Projects/Feature/Onboarding/Sources/OnboardingSignUpView.swift
  Projects/Feature/Sources/Root.swift
  Projects/Feature/Sources/RootView.swift
  Projects/Feature/Sources/TabBarView.swift
  README.md
  Tuist/Signing/AppWatch.Debug.mobileprovision
  Tuist/Signing/AppWatch.Release.mobileprovision
  Tuist/Signing/AppWatchExtension.Debug.mobileprovision
  Tuist/Signing/AppWatchExtension.Release.mobileprovision
Labels: size/l

#44 [Feat/#35] Network Generic Layer 구현 (Interceptor, Monitor 미구현)
  Makefile
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+Modules.swift
  Projects/Core/Network/Interface/Sources/Endpoint/EndPoint.swift
  Projects/Core/Network/Interface/Sources/Endpoint/HTTPMethods.swift
  Projects/Core/Network/Interface/Sources/Endpoint/RequestableInterface.swift
  Projects/Core/Network/Interface/Sources/Endpoint/ResponsableInterface.swift
  Projects/Core/Network/Interface/Sources/NetworkError.swift
  Projects/Core/Network/Interface/Sources/NetworkInterfaceSample.swift
  Projects/Core/Network/Interface/Sources/NetworkProviderInterface.swift
  Projects/Core/Network/Project.swift
  Projects/Core/Network/Sources/EndPoint/Requestable.swift
  Projects/Core/Network/Sources/NetworkProvider.swift
  Projects/Core/Network/Sources/NetworkSample.swift
  Projects/Shared/Project.swift
  Projects/Shared/Util/Interface/Sources/UtilInterface.swift
  Projects/Shared/Util/Project.swift
  Projects/Shared/Util/Sources/Source.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  graph.png
Labels: size/m

#48 [Feat/#47] 프로비저닝 프로필 디바이스 추가
  Tuist/Signing/AppWatch.Debug.mobileprovision
  Tuist/Signing/AppWatchExtension.Debug.mobileprovision
  Tuist/Signing/Pumping.Debug.mobileprovision
Labels: size/xs

#46 [Feat/#42] 모듈의 Interface 분리를 위한 Root Reducer의 Composition Root 적용
  Projects/Feature/Home/Project.swift
  Projects/Feature/MyPage/Project.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingNickname.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingRoot.swift
  Projects/Feature/Onboarding/Interface/Sources/OtherProfile.swift
  Projects/Feature/Onboarding/Interface/Sources/OtherProfileDetail.swift
  Projects/Feature/Onboarding/Sources/OnboardingNickname/OnboardingNicknameView.swift
  Projects/Feature/Onboarding/Sources/OnboardingRoot/OnboardingRootStore.swift
  Projects/Feature/Onboarding/Sources/OnboardingRoot/OnboardingRootView.swift
  Projects/Feature/Onboarding/Sources/OnboardingSignUp/OnboardingSignUpView.swift
  Projects/Feature/Onboarding/Sources/OtherProfile/OtherProfileStore.swift
  Projects/Feature/Onboarding/Sources/OtherProfile/OtherProfileView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailStore.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailView.swift
  Projects/Feature/Sources/Root.swift
Labels: size/m

#51 [Feat/#45] key chain store 구축
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Core/KeyChainStore/Interface/Sources/TokenStoreInterface.swift
  Projects/Core/KeyChainStore/Project.swift
  Projects/Core/KeyChainStore/Sources/KeyChainStore.swift
  Projects/Core/KeyChainStore/Testing/Sources/KeyChainStoreTesting.swift
  Projects/Core/KeyChainStore/Tests/Sources/KeyChainStoreTest.swift
  Projects/Core/Network/Interface/Sources/Endpoint/RequestableInterface.swift
  Projects/Core/Project.swift
  Projects/Domain/Auth/Interface/Sources/Local/LocalAuthStoreInterface.swift
  Projects/Domain/Auth/Interface/Sources/Models/Models.swift
  Projects/Domain/Auth/Interface/Sources/Models/Token.swift
  Projects/Domain/Auth/Interface/Sources/Remote/AuthClient.swift
  Projects/Domain/Auth/Sources/Local/LocalAuthStore.swift
  Projects/Domain/Auth/Sources/Remote/AuthClient.swift
Labels: size/m

#53 [Feat/#52] 운동중 UI 구현 1차
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Feature/Project.swift
  Projects/Feature/Workout/Example/Sources/AppView.swift
  Projects/Feature/Workout/Interface/Sources/WorkoutEnd.swift
  Projects/Feature/Workout/Interface/Sources/WorkoutHome.swift
  Projects/Feature/Workout/Interface/Sources/WorkoutRoot.swift
  Projects/Feature/Workout/Interface/Sources/WorkoutStart.swift
  Projects/Feature/Workout/Interface/Sources/WorkoutTimer.swift
  Projects/Feature/Workout/Project.swift
  Projects/Feature/Workout/Sources/End/WorkoutEndStore.swift
  Projects/Feature/Workout/Sources/End/WorkoutEndView.swift
  Projects/Feature/Workout/Sources/Home/WorkoutHomeStore.swift
  Projects/Feature/Workout/Sources/Home/WorkoutHomeView.swift
  Projects/Feature/Workout/Sources/Root/WorkoutRootStore.swift
  Projects/Feature/Workout/Sources/Root/WorkoutRootView.swift
  Projects/Feature/Workout/Sources/Start/WorkoutStartStore.swift
  Projects/Feature/Workout/Sources/Start/WorkoutStartView.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerStore.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerView.swift
  Projects/Feature/Workout/Testing/Sources/WorkoutTesting.swift
  Projects/Feature/Workout/Tests/Sources/WorkoutTest.swift
Labels: size/l

#62 [Feat/#57] 운동 Root UI 구현
  Projects/Feature/Workout/Sources/Root/WorkoutRootView.swift
Labels: size/s

#63 [Feat/#59] 운동 Start UI 구현
  Projects/Feature/Workout/Sources/Start/WorkoutStartView.swift
Labels: size/s

#65 [Feat/#58] 운동 Home UI 구현
  Projects/Feature/Workout/Interface/Sources/WorkoutHome.swift
  Projects/Feature/Workout/Sources/Home/WorkoutHomeStore.swift
  Projects/Feature/Workout/Sources/Home/WorkoutHomeView.swift
  Projects/Shared/DesignSystem/Sources/Cell/PumpingTextCellView.swift
  Projects/Shared/DesignSystem/Sources/Cell/PumpintTextCellStore.swift
Labels: size/m

#66 [Feat/#60] 운동 Timer UI 구현
  Projects/Feature/Workout/Interface/Sources/WorkoutTimer.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerStore.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerView.swift
  Projects/Shared/DesignSystem/Sources/TimerCellStore.swift
  Projects/Shared/DesignSystem/Sources/TimerCellView.swift
Labels: size/m
