Repository depromeet/Pumping-iOS, pull requests merged in 2023-07, with the labels that each got.

#115 [Feat/#114] Shared Cell Feature로 이동
  Projects/Feature/Crew/Interface/Sources/CrewRanking/Cells/CrewRankingCellView.swift
  Projects/Feature/Crew/Interface/Sources/CrewRanking/Cells/CrewRankingStore.swift
  Projects/Feature/Crew/Interface/Sources/CrewRanking/CrewRankingView.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/PersonalRecordCellStore.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/PersonalRecordCellView.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/ProfileBodyCellStore.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/ProfileBodyCellView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewHomeStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewHomeView.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Crew/Sources/Root/CrewRootStore.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Cells/ProfileWeekDayCellStore.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Cells/ProfileWeekDayCellView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/ProfileView.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/Cells/WidthOfChangeCellStore.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/Cells/WidthOfChangeCellView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/thumbsUp.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/thumbsUp.imageset/Icon (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/thumbsUp.imageset/Icon (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/thumbsUp.imageset/Icon.png
Labels: size/l

#119 [BugFix/#118] import 버그 해결
  Projects/App/Sources/RootStore.swift
  Projects/Core/KeyChainStore/Project.swift
  Projects/Domain/Crew/Project.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Crew/Sources/Root/CrewRootStore.swift
  Projects/Feature/Sources/MainTabViewStore.swift
  graph.png
Labels: size/s

#124 [Feat/#113] CrewJoin API 개발 완료
  Projects/App/Sources/RootStore.swift
  Projects/Domain/Crew/Interface/Sources/CrewClient.swift
  Projects/Domain/Crew/Interface/Sources/CrewEndpoint.swift
  Projects/Domain/Crew/Interface/Sources/DTO/Response/CrewResponseDTO.swift
  Projects/Domain/Crew/Interface/Sources/Models/CrewInfo.swift
  Projects/Domain/Crew/Sources/CrewClient.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewJoin/CrewJoinStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewJoin/CrewJoinView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewMake/CrewMakeStoreInterface.swift
  Projects/Feature/Crew/Sources/Home/CrewJoin/CrewJoinStore.swift
  Projects/Feature/Crew/Sources/Home/CrewMake/CrewMakeStore.swift
Labels: size/s

#121 [Feat/#116] Workout API 연동
  Projects/App/Sources/RootApp.swift
  Projects/App/Sources/RootStore.swift
  Projects/Core/HealthKit/Interface/Sources/HealthKitError.swift
  Projects/Core/HealthKit/Interface/Sources/HealthKitManagerInterface.swift
  Projects/Core/HealthKit/Interface/Sources/HealthKitManagerType.swift
  Projects/Core/HealthKit/Sources/HealthKitManager.swift
  Projects/Core/HealthKitManager/Interface/Sources/HealthKitAuthorizationHelperInterface.swift
  Projects/Core/HealthKitManager/Interface/Sources/HealthKitError.swift
  Projects/Core/HealthKitManager/Interface/Sources/HealthKitManagerInterface.swift
  Projects/Core/HealthKitManager/Project.swift
  Projects/Core/HealthKitManager/Sources/HealthKitAuthorizationHelper.swift
  Projects/Core/HealthKitManager/Sources/HealthKitManager.swift
  Projects/Core/Project.swift
  Projects/Core/Sources/CoreExport.swift
  Projects/Domain/Workout/Interface/Sources/DTO/Request/MakeWorkoutRequestDTO.swift
  Projects/Domain/Workout/Interface/Sources/DTO/Response/MakeWorkoutResponseDTO.swift
  Projects/Domain/Workout/Interface/Sources/Models/PumpingTimer.swift
  Projects/Domain/Workout/Interface/Sources/Models/WorkoutCategory.swift
  Projects/Domain/Workout/Interface/Sources/WorkoutClient.swift
  Projects/Domain/Workout/Interface/Sources/WorkoutEndpoint.swift
  Projects/Domain/Workout/Interface/Sources/WorkoutInterface.swift
  Projects/Domain/Workout/Sources/Source.swift
  Projects/Domain/Workout/Sources/WorkoutClient.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingPermission/OnboardingPermissionView.swift
  Projects/Feature/Onboarding/Sources/OnboardingPermission/OnboardingPermissionStore.swift
  Projects/Feature/Workout/Interface/Sources/End/Components/Cells/WorkoutTimerSummaryCellView.swift
  Projects/Feature/Workout/Interface/Sources/End/WorkoutEndStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/End/WorkoutEndView.swift
  Projects/Feature/Workout/Interface/Sources/Home/Components/Cells/WorkoutCategoryCellView.swift
  Projects/Feature/Workout/Interface/Sources/Start/WorkoutStartView.swift
  Projects/Feature/Workout/Interface/Sources/Timer/Components/Cells/WorkoutTimerCellView.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutTimerView.swift
  Projects/Feature/Workout/Sources/End/WorkoutEndStore.swift
  Projects/Feature/Workout/Sources/Root/WorkoutRootStore.swift
Labels: size/xl

#131 [Feat/#128] 프로필 화면 재구성
  Projects/Domain/Workout/Interface/Sources/DTO/Response/FetchWorkoutResponseDTO.swift
  Projects/Domain/Workout/Interface/Sources/Models/ProfileWorkoutInfo.swift
  Projects/Domain/Workout/Interface/Sources/Models/PumpingTimer.swift
  Projects/Domain/Workout/Interface/Sources/Models/WorkoutCategory.swift
  Projects/Domain/Workout/Interface/Sources/WorkoutClient.swift
  Projects/Domain/Workout/Interface/Sources/WorkoutEndpoint.swift
  Projects/Domain/Workout/Sources/WorkoutClient.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Crew/Sources/Root/CrewRootStore.swift
  Projects/Feature/Profile/Interface/Sources/Home/ProfileHomeStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/Home/ProfileHomeView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Cells/ProfileWeekDayCellStore.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Cells/ProfileWeekDayCellView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/First/ProfileWorkoutTimeView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/ProfileHeaderView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/ProfileStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/Profile/ProfileView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Secondary/ProfileCalorieView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Secondary/ProfileHeartRateView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Third/ProfileWorkoutDataView.swift
  Projects/Feature/Profile/Interface/Sources/ProfileRootView.swift
  Projects/Feature/Profile/Interface/Sources/Root/ProfileRootStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/Root/ProfileRootView.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/ProfileWidthOfChangeStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/ProfileWidthOfChangeView.swift
  Projects/Feature/Profile/Sources/Home/ProfileHomeStore.swift
  Projects/Feature/Profile/Sources/Root/ProfileRootStore.swift
  Projects/Feature/Profile/Sources/WidthOfChange/ProfileWidthOfChangeStore.swift
  Projects/Feature/Sources/MainTabView.swift
  Projects/Feature/Sources/MainTabViewStore.swift
  Projects/Feature/Workout/Interface/Sources/Home/Components/Cells/WorkoutCategoryCellStore.swift
  Projects/Feature/Workout/Interface/Sources/Home/WorkoutHomeStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Start/WorkoutStartStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutTimerStoreInterface.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_fire.imageset/Component 3.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_fire.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_heartRate.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_heartRate.imageset/Icon (1).svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_timer.imageset/Component 4.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_timer.imageset/Contents.json
  Projects/Shared/DesignSystem/Sources/Components/Text/TenadaFont.swift
  Projects/Shared/DesignSystem/Sources/Font.swift
  Projects/Shared/DesignSystem/Sources/PumpingFont.swift
Labels: size/xl

#133 [Feat/#132] timer 종료시에 watch의 운동 종료
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/App/WatchExtension/Sources/App/WatchConnectivityDelegate.swift
  Projects/App/WatchExtension/Sources/App/WorkoutDelegate.swift
  Projects/App/WatchExtension/Sources/Domain/WatchConnectivityControl.swift
  Projects/App/WatchExtension/Sources/Feature/Home/HomeView.swift
  Projects/Domain/Project.swift
  Projects/Domain/Sources/DomainExport.swift
  Projects/Domain/WatchConnectivity/Interface/Sources/WatchConnectivityControl.swift
  Projects/Domain/WatchConnectivity/Interface/Sources/WatchConnectivityDelegate.swift
  Projects/Domain/WatchConnectivity/Project.swift
  Projects/Domain/WatchConnectivity/Sources/Source.swift
  Projects/Domain/WatchConnectivity/Testing/Sources/WatchConnectivityTesting.swift
  Projects/Domain/WatchConnectivity/Tests/Sources/WatchConnectivityTest.swift
  Projects/Feature/Workout/Interface/Sources/Root/WorkoutRootView.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutTimerView.swift
Labels: size/m

#135 [Feat/#134] 테스트 플라이트 업로드
  Projects/App/Project.swift
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/100.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/102.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/1024.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/114.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/120.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/128.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/144.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/152.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/16.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/167.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/172.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/180.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/196.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/20.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/216.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/256.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/32.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/48.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/50.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/512.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/55.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/58.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/60.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/64.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/66.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/72.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/76.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/80.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/87.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/88.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/92.png
  Projects/App/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Images.xcassets/Contents.json
  Projects/WatchShared/DesignSystem/Project.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: size/m

#144 [Feat/#143] Home-API-대응
  Projects/Feature/Crew/Interface/Sources/Home/Cells/PersonalRecordCellStore.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/PersonalRecordCellView.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/ProfileBodyCellStore.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/ProfileBodyCellView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewHomeStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewHomeView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewListView.swift
  Projects/Feature/Crew/Sources/Home/CrewHomeStore.swift
Labels: size/m

#145 [Feat/#142] 1차 출시 다시 시도
  Projects/App/Project.swift
  Projects/App/Sources/RootStore.swift
  Projects/App/WatchExtension/Sources/Domain/PumpingTimer.swift
  Projects/App/WatchExtension/Sources/Domain/WorkoutCategory.swift
  Projects/App/WatchExtension/Sources/Feature/Home/Components/Cells/TimerCellView.swift
  Projects/App/WatchExtension/Sources/Feature/Home/HomeView.swift
  Projects/Domain/Workout/Interface/Sources/DTO/Response/FetchWorkoutResponseDTO.swift
  Projects/Domain/Workout/Interface/Sources/Models/ProfileWorkoutInfo.swift
  Projects/Feature/Crew/Interface/Sources/Home/Cells/ProfileBodyCellView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewHomeView.swift
  Projects/Feature/Crew/Interface/Sources/Home/CrewMake/CrewMakeCompleteView.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Profile/Interface/Sources/Home/ProfileHomeStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/Home/ProfileHomeView.swift
  Projects/Feature/Profile/Sources/Home/ProfileHomeStore.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/img_crew.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/img_crew.imageset/img_crew.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/img_crew.imageset/img_crew@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/img_crew.imageset/img_crew@3x.png
  Projects/Shared/Util/Sources/Extensions/Date.swift
  README.md
  graph.png
Labels: size/m
