Repository depromeet/Pumping-iOS, pull requests merged in 2023-06, with the labels that each got.

#69 [Feat/#68] profile UI 구현
  Projects/Feature/Onboarding/Interface/Sources/OtherProfileDetail.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailStore.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileCalorieView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileHeaderView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileHeartRateView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWeekDaysView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWorkoutDataView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWorkoutTimeView.swift
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Black.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Bold.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-ExtraBold.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-ExtraLight.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Light.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Medium.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Regular.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-SemiBold.otf
  Projects/Shared/DesignSystem/Resources/Font/Pretendard/Pretendard-Thin.otf
  Projects/Shared/DesignSystem/Resources/Font/Tenada/Tenada.ttf
  Projects/Shared/DesignSystem/Resources/Images.xcassets/clock.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/clock.imageset/Exclude (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/clock.imageset/Exclude (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/clock.imageset/Exclude.png
  Projects/Shared/DesignSystem/Sources/Font.swift
Labels: help wanted, size/m

#79 [Feat/#76] 운동중 디테일 UI 수정 - 타이머 구현
  Projects/Domain/Auth/Interface/Sources/Remote/AuthClient.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingAuth/OnboardingAuthStoreInterface.swift
  Projects/Feature/Onboarding/Sources/OnboardingAuth/OnboardingAuthStore.swift
  Projects/Feature/Onboarding/Sources/OnboardingRoot/OnboardingRootStore.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailStore.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/OtherProfileDetailView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileCalorieView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileHeaderView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileHeartRateView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWeekDaysView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWorkoutDataView.swift
  Projects/Feature/Onboarding/Sources/OtherProfileDetail/ProfileWorkoutTimeView.swift
  Projects/Feature/Workout/Interface/Sources/Counter/WorkoutCounterStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Counter/WorkoutCounterView.swift
  Projects/Feature/Workout/Interface/Sources/End/WorkoutEndStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/End/WorkoutEndView.swift
  Projects/Feature/Workout/Interface/Sources/Home/WorkoutHomeStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Home/WorkoutHomeView.swift
  Projects/Feature/Workout/Interface/Sources/Root/WorkoutRootStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Root/WorkoutRootView.swift
  Projects/Feature/Workout/Interface/Sources/Start/WorkoutStartStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Start/WorkoutStartView.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutConterView.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutTimerStoreInterface.swift
  Projects/Feature/Workout/Interface/Sources/Timer/WorkoutTimerView.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerView.swift
  Projects/Feature/Workout/Sources/WorkoutCounterStore.swift
  Projects/Feature/Workout/Sources/WorkoutEndStore.swift
  Projects/Feature/Workout/Sources/WorkoutHomeStore.swift
  Projects/Feature/Workout/Sources/WorkoutRootStore.swift
  Projects/Feature/Workout/Sources/WorkoutStartStore.swift
  Projects/Feature/Workout/Sources/WorkoutTimerStore.swift
  Projects/Shared/DesignSystem/Resources/Colors.xcassets/ColorGrey000.colorset/Contents.json
  Projects/Shared/DesignSystem/Sources/Cell/PumpingTextCellView.swift
  graph.png
Labels: size/l

#85 [Feat/#72] Profile widthofchange UI 구현
  Projects/Feature/Profile/Interface/Sources/Profile/First/ProfileWorkoutTimeView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/ProfileWeekDaysView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Secondary/ProfileCalorieView.swift
  Projects/Feature/Profile/Interface/Sources/Profile/Secondary/ProfileHeartRateView.swift
  Projects/Feature/Profile/Interface/Sources/ProfileRootStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/ProfileRootView.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/WidthOfChangeStoreInterface.swift
  Projects/Feature/Profile/Interface/Sources/WidthOfChange/WidthOfChangeView.swift
  Projects/Feature/Profile/Sources/ProfileRootStore.swift
  Projects/Feature/Profile/Sources/WidthOfChangeStore.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrow.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrow.imageset/Frame 48096355 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrow.imageset/Frame 48096355 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrow.imageset/Frame 48096355.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrowForPercentage.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrowForPercentage.imageset/arrowUp.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrowForPercentage.imageset/arrowUp1.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/arrowForPercentage.imageset/arrowUp2.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeCalorie.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeCalorie.imageset/widthOfChange_Calorie.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeCalorie.imageset/widthOfChange_Calorie1.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeCalorie.imageset/widthOfChange_Calorie2.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeHearRate.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeHearRate.imageset/widthOfChange_HearRate.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeHearRate.imageset/widthOfChange_HearRate1.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeHearRate.imageset/widthOfChange_HearRate2.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeMaxWorkoutPart.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeMaxWorkoutPart.imageset/widthOfChange_MaximumPart.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeMaxWorkoutPart.imageset/widthOfChange_MaximumPart1.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeMaxWorkoutPart.imageset/widthOfChange_MaximumPart2.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeWorkoutTime.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeWorkoutTime.imageset/widthOfChange_workoutTime.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeWorkoutTime.imageset/widthOfChange_workoutTime1.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/widthOfChangeWorkoutTime.imageset/widthOfChange_workoutTime2.png
  Projects/Shared/DesignSystem/Sources/Cell/Profile/ProfileWeekDayCellStore.swift
  Projects/Shared/DesignSystem/Sources/Cell/Profile/ProfileWeekDayCellView.swift
  Projects/Shared/DesignSystem/Sources/Cell/Profile/WidthOfChange/WidthOfChangeCellStore.swift
  Projects/Shared/DesignSystem/Sources/Cell/Profile/WidthOfChange/WidthOfChangeCellView.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: help wanted, size/l

#93 [Feat/#88] 공통 컴포넌트 정리
  Projects/App/Project.swift
  Projects/App/Sources/RootStore.swift
  Projects/Core/KeyChainStore/Interface/Sources/TokenStoreInterface.swift
  Projects/Core/Network/Interface/Sources/Endpoint/EndPoint.swift
  Projects/Core/Network/Sources/NetworkProvider.swift
  Projects/Domain/Auth/Interface/Sources/DTO/SignInWithAppleRequestDTO.swift
  Projects/Domain/Auth/Interface/Sources/DTO/SignInWithAppleResponseDTO.swift
  Projects/Domain/Auth/Interface/Sources/DTO/SignOutRequest.swift
  Projects/Domain/Auth/Interface/Sources/DTO/SignOutResponse.swift
  Projects/Domain/Auth/Interface/Sources/Local/LocalAuthStoreInterface.swift
  Projects/Domain/Auth/Interface/Sources/Models/Token.swift
  Projects/Domain/Auth/Interface/Sources/Remote/AuthClient.swift
  Projects/Domain/Auth/Interface/Sources/Remote/AuthEndpoint.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/LocalAuthStore.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingAuth/OnboardingAuthStoreInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingAuth/OnboardingAuthView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingAvatar/OnboardingAvatarInterfaceStore.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingAvatar/OnboardingAvatarView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingPermission/OnboardingPermissionStoreInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingPermission/OnboardingPermissionView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingProfile/OnboadingProfileStoreInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingProfile/OnboardingProfileView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingRoot/OnboardingRootStoreInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingRoot/OnboardingRootView.swift
  Projects/Feature/Onboarding/Interface/Sources/OnboardingRoot/OnboardingScene.swift
  Projects/Feature/Onboarding/Sources/OnboardingAuth/OnboardingAuthStore.swift
  Projects/Feature/Onboarding/Sources/OnboardingRoot/OnboardingRootStore.swift
  Projects/Feature/Sources/MainTabView.swift
  Projects/Feature/Sources/MainTabViewStore.swift
  Projects/Shared/DesignSystem/Sources/Components/BottomSheet/BasicBottomSheet.swift
  Projects/Shared/DesignSystem/Sources/Components/Modal/BasicModal.swift
Labels: size/m

#101 [Feat/#96] 커스텀 탭바 추가
  Projects/App/Sources/RootStore.swift
  Projects/Feature/Sources/MainScene.swift
  Projects/Feature/Sources/MainTabView.swift
  Projects/Feature/Sources/MainTabViewStore.swift
  Projects/Feature/Workout/Sources/Counter/WorkoutCounterStore.swift
  Projects/Feature/Workout/Sources/End/WorkoutEndStore.swift
  Projects/Feature/Workout/Sources/Home/WorkoutHomeStore.swift
  Projects/Feature/Workout/Sources/Root/WorkoutRootStore.swift
  Projects/Feature/Workout/Sources/Start/WorkoutStartStore.swift
  Projects/Feature/Workout/Sources/Timer/WorkoutTimerStore.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/home.imageset/Component 1.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/home.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/mypage.imageset/Component 1 (1).svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/mypage.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/workout.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/workout.imageset/Subtract (1).svg
  Projects/Shared/DesignSystem/Sources/Component/PumpingButtonStyle.swift
  Projects/Shared/Util/Sources/Managers/DateManager.swift
Labels: size/m

#97 [Feat/#92] 부모 모듈 import로 하위 모듈 한번에 가져오기
  Projects/App/Sources/RootApp.swift
  Projects/App/Sources/RootStore.swift
  Projects/App/Sources/RootView.swift
  Projects/Core/CoreExport.swift
  Projects/Core/Sources/CoreRoot.swift
  Projects/Domain/DomainExport.swift
  Projects/Domain/Sources/ContentView.swift
  Projects/Domain/Sources/DomainRoot.swift
  Projects/Feature/FeatureExport.swift
  Projects/Feature/Sources/MainTabView.swift
  Projects/Feature/Sources/MainTabViewStore.swift
  Projects/Shared/SharedExport.swift
  Projects/Shared/Sources/HomeInterfaceSample.swift
  Projects/Shared/Sources/SharedRoot.swift
Labels: size/m

#99 [Feat/#90] profile refactoring UI
  Projects/Feature/Crew/Interface/Sources/Ranking/CrewRankingStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Ranking/CrewRankingView.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Crew/Sources/Ranking/CrewRankingStore.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardio.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardio.imageset/Frame 48096425 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardio.imageset/Frame 48096425 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardio.imageset/Frame 48096425.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardioAvatar.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardioAvatar.imageset/Group 481673 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardioAvatar.imageset/Group 481673 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingCardioAvatar.imageset/Group 481673.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlace.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlace.imageset/Frame 48096427 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlace.imageset/Frame 48096427 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlace.imageset/Frame 48096427.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlaceAvatar.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlaceAvatar.imageset/Group 481903 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlaceAvatar.imageset/Group 481903 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLastPlaceAvatar.imageset/Group 481903.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBody.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBody.imageset/Frame 48096426 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBody.imageset/Frame 48096426 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBody.imageset/Frame 48096426.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBodyAvatar.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBodyAvatar.imageset/Group 481732 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBodyAvatar.imageset/Group 481732 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingLowerBodyAvatar.imageset/Group 481732.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingUpperBody.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingUpperBody.imageset/Group 481902 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingUpperBody.imageset/Group 481902 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingUpperBody.imageset/Group 481902.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTime.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTime.imageset/Frame 48096428 (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTime.imageset/Frame 48096428 (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTime.imageset/Frame 48096428.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTimeAvatar.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTimeAvatar.imageset/alarm clock (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTimeAvatar.imageset/alarm clock (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/crewRankingWorkoutCumulativeTimeAvatar.imageset/alarm clock.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/strongArm.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/strongArm.imageset/Vector (1).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/strongArm.imageset/Vector (2).png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/strongArm.imageset/Vector.png
  Projects/Shared/DesignSystem/Sources/Cells/CrewRanking/CrewRankingCellView.swift
  Projects/Shared/DesignSystem/Sources/Cells/CrewRanking/CrewRankingStore.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: size/l

#105 [Feat#103] Watch UI 구현
  Projects/App/Project.swift
  Projects/App/Pumping.entitlements
  Projects/App/WatchExtension/Sources/View/ActivityRingsView.swift
  Projects/App/WatchExtension/Sources/View/ControlsView.swift
  Projects/App/WatchExtension/Sources/View/ElapsedTimeView.swift
  Projects/App/WatchExtension/Sources/View/MetricsView.swift
  Projects/App/WatchExtension/Sources/View/SessionPagingView.swift
  Projects/App/WatchExtension/Sources/View/StartView.swift
  Projects/App/WatchExtension/Sources/View/SummaryView.swift
  Projects/App/WatchExtension/Sources/WatchApp.swift
  Projects/App/WatchExtension/Sources/WorkoutManager.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootStoreInterface.swift
  Projects/Feature/Crew/Interface/Sources/Root/CrewRootView.swift
  Projects/Feature/Crew/Sources/Root/CrewRootStore.swift
  Tuist/Signing/AppWatchExtension.Debug.mobileprovision
  Tuist/Signing/AppWatchExtension.Release.mobileprovision
Labels: size/l
